### 📨 Send Fanout Message
POST http://localhost:5003/send/fanout
Content-Type: application/json

{
  "userName": "john.doe",
  "emailAddress": "john@example.com",
  "zipCode": "10115",
  "content": "Test fanout message from HTTP file"
}

