### 📨 Send Fanout Message
POST http://localhost:5003/send/fanout
Content-Type: application/json

{
  "userName": "jose.doe",
  "emailAddress": "jose@example.com",
  "zipCode": "10117",
  "content": "Test fanout message from HTTP file"
}

